List9 = {
    "About To Happen": ["Imminent", "Impending(-)"],
    "Careless": ["Lax", "Negligent", "Remiss", "Slipshod", "Stringent(opposite)"],
    "Confirm or Declare": [
        "Affirm",
        "Ascertain",
        "Assert",
        "Aver",
        "Avow",
        "Contend",
        "Proclaim",
        "Testimony",
    ],
    "Easily Affected(-)": [
        "Prone",
        "Subject To",
        "Susceptible",
        "Vulnerable",
        "Impervious(opposite)",
    ],
    "Enter Without Permission": [
        "Encroach",
        "Impinge",
        "Infringe",
        "Intrude",
        "Obtrude",
    ],
    "Examine Carefully": ["Peruse", "Pore Over", "Scrutinize", "Browse(neutral)"],
    "Friendly": [
        "Affable",
        "Amiable",
        "Amicable",
        "Camaraderie",
        "Complaisance",
        "Congenial",
        "Convivial",
        "Cordial",
        "Fraternize",
        "Genial",
        "Gregarious",
        "Aloof(opposite)",
        "Frigid(opposite)",
        "Glacial(opposite)",
    ],
    "Give Up": [
        "Abdicate",
        "Abjure",
        "Abnegate",
        "Cede",
        "Forgo",
        "Forsake",
        "Forswear",
        "Relinquish",
        "Renounce",
    ],
    "Hide or Cover or Disguise": [
        "Camouflage",
        "Cloak",
        "Dissemble",
        "Feign",
        "Guise",
        "Incognito",
        "Mask",
        "Masquerade",
        "Shroud",
        "Veneer",
    ],
    "Imitate or Comic Imitation(neutral)": [
        "Emulate",
        "Simulate",
        "Mimic(neutral)",
        "Pastiche",
    ],
    "Inspiring Fear or Respect": ["Awe", "Formidable", "Redoubtable"],
    "Irritable": [
        "Cantankerous",
        "Chagrin",
        "Choleric",
        "Churlish",
        "Curmudgeon",
        "Grouchy",
        "Gruff",
        "Irascible",
        "Testiness",
    ],
    "Mediator or Lead(neutral)": [
        "Arbiter",
        "Arbitrator",
        "Mediate",
        "Officiate(neutral)",
        "Preside(neutral)",
    ],
    "Offensivel or Lusty": [
        "Lascivious",
        "Leer",
        "Lewd",
        "Lurid",
        "Obscene",
        "Seamy",
        "Sordid",
        "Vulgar",
    ],
    "Respect": [
        "Commemorate",
        "Deference",
        "Exalt",
        "Hallow",
        "Homage",
        "Revere",
        "Venerate",
    ],
    "Secret(-)": [
        "Clandestine",
        "Covert",
        "Furtive",
        "Oblique",
        "Skulk",
        "Sly",
        "Stealth",
        "Surreptitious",
        "Overt(opposite)",
    ],
    "Take Away Forcibly": ["Appropriate", "Divest", "Expropriate", "Preempt", "Usurp"],
    "To Irritate or Make Angry": [
        "Disgruntled",
        "Exasperate",
        "Grate",
        "Harangue",
        "Heckle",
        "Indignation",
        "Infuriate",
        "Irksome",
        "Miffed",
        "Nag",
        "Nettle",
        "Peeve",
        "Pique",
        "Vex",
    ],
    "To Think Deeply": [
        "Cogitate",
        "Contemplate",
        "Deliberate",
        "Introspect",
        "Mull",
        "Muse",
        "Pensive",
        "Ponder",
        "Reflect",
        "Ruminate",
    ],
}
