List10 = {
    "Accuse or Defame": [
        "Aspersion",
        "Calumny",
        "Defame",
        "Libel",
        "Malign",
        "Obloquy",
        "Opprobrium",
        "Slander",
        "Slur",
        "Stigmatization",
        "Vilify",
    ],
    "Alert": ["Vigilant", "Disarm(opposite)", "Inattentive"],
    "Attract or Fascinate": [
        "Arresting",
        "Captivate",
        "Delectable",
        "Enamored",
        "Enthrall",
        "Infatuate",
        "Mesmerize",
        "Rapture",
        "Spellbinding",
        "Ennui(opposite)",
    ],
    "Beginner or Inexperienced": [
        "Apprentice",
        "Dilettante",
        "Novel",
        "Novice",
        "Rookie",
    ],
    "Brave": [
        "Audacious",
        "Chivalry",
        "Dauntless",
        "Gallant",
        "Intrepid",
        "Pluck",
        "Undaunted",
        "Valiant",
        "Valor",
    ],
    "Contradict Itself": ["Irony or Ironic", "Paradox"],
    "Counter Attack": ["Retaliate", "Reprisal"],
    "Cure All": ["Panacea", "Elixir"],
    "Delay or Postpone": ["Adjourn", "Defer", "Protract", "Procrastinate"],
    "Disrepute or Bad Reputation": ["Ignominy", "Infamy", "Nefarious", "Notorious"],
    "Embarrass": ["Abash", "Discomfit", "Mortify"],
    "Fake or False or Doubtful": [
        "Apocryphal",
        "Dubious",
        "Erroneous",
        "Ersatz",
        "Fabricate",
        "Fallacious",
        "Illicit",
        "Phony",
        "Sham",
        "Sophistry",
        "Specious",
        "Spurious",
        "Propaganda",
    ],
    "Falsehood": ["Mendacity", "Perjury", "Prevarication", "Veracity(opposite)"],
    "Fearful or Lacking Courage": [
        "Cower",
        "Craven",
        "Cringe",
        "Daunt",
        "Flinch",
        "Petrify",
        "Pusillanimous",
        "Shrink",
        "Trepidation",
    ],
    "Fluent or Clear": [
        "Articulate",
        "Coherent",
        "Eloquent",
        "Enunciate",
        "Glib(smooth Talker)",
        "Labored(opposite)",
        "Ineffable(opposite)",
    ],
    "Genuine": [
        "Authentic",
        "Legitimate",
        "Veritable",
        "Counterfeit(opposite)",
        "Factitious(opposite)",
    ],
    "Gloomy or Dark": ["Bleak", "Somber"],
    "Illogical or Strange": [
        "Absurd",
        "Atypical",
        "Bizarre",
        "Ludicrous",
        "Outlandish",
        "Preposterous",
        "Uncanny",
    ],
    "Immature": ["Callow", "Puerile"],
    "Native or Local": ["Indigenous", "Exotic(opposite)"],
    "Puzzling": [
        "Conundrum",
        "Cryptic",
        "Enigma",
        "Garble",
        "Inscrutable",
        "Intrigue",
        "Labyrinth",
        "Maze",
    ],
    "Rude": ["Boor", "Brusque", "Curt", "Terse"],
    "Shy or Introvert": [
        "Coy",
        "Diffidence",
        "Reserved",
        "Retiring",
        "Timid",
        "Timorous",
    ],
    "Unintentionally": ["Inadvertently", "Unwittingly"],
    "Widespread(-)": ["Epidemic", "Pandemic", "Rampant", "Endemic(opposite)", "Rife"],
    "Working Under Another": ["Subordinate", "Underling"],
}
