List11 = {
    "Artificial or Pretense": [
        "Affected",
        "Contrived",
        "Mannered",
        "Posture",
        "Pretentious",
    ],
    "Aware or Unaware (Opposite)": ["Cognizant", "Oblivious(Opposite)"],
    "Best Example": [
        "Apotheosis",
        "Archetype",
        "Embody",
        "Epitome",
        "Exemplify",
        "Paradigm",
        "Paragon",
        "Personify",
        "Prototype(Neutral)",
    ],
    "Force or Put Pressure": [
        "Coercion",
        "Compel",
        "Compulsion",
        "Extort",
        "Press",
        "Dissuade",
    ],
    "Get Rid Of or Cleanse": ["Catharsis", "Expurgate", "Purge"],
    "Go Off Track": [
        "Astray",
        "Awry",
        "Circuitous",
        "Desultory",
        "Digress",
        "Discursive",
        "Divergent",
        "Ramble",
        "Tangential",
    ],
    "Important Mark": ["Hallmark", "Landmark", "Milestone", "Watershed"],
    "Impure or Poisonous": ["Adulterate", "Contaminate", "Noxious", "Toxic", "Vitiate"],
    "Inborn or Firmly Fixed": [
        "Congenital",
        "Entrenched",
        "Inherent",
        "Innate",
        "Intrinsic",
    ],
    "Intelligent or Wise": [
        "Acuity",
        "Acumen",
        "Astute",
        "Discerning",
        "Discriminating",
        "Insightful",
        "Judicious",
        "Perceptive",
        "Perspicacious",
        "Prudent",
        "Sagacious",
        "Sage",
        "Savant",
        "Impolitic(Opposite)",
        "Shrewd(Neutral)",
        "Canny",
        "Simpleton(Opposite)",
    ],
    "Not Sacred or Worldly": ["Secular", "Temporal"],
    "Persuade or Flatter": [
        "Cajole",
        "Coax",
        "Cogent",
        "Enjoin",
        "Exhort",
        "Induce",
        "Urge",
        "Wheedle",
        "Woo(Neutral)",
        "Blandishment",
        "Court",
    ],
    "Plead": ["Behest", "Beseech", "Entreaty", "Implore", "Importune", "Supplicate"],
    "Prove To Be Right": [
        "Gratuitous(Opposite)",
        "Justifiable",
        "Necessitate",
        "Warrant",
        "Indefensible(Opposite)",
        "Untenable(Opposite)",
    ],
    "Spoil or Disfigure": ["Deface", "Distort", "Mar", "Warp", "Impair"],
    "Spotted or Stained": ["Blemish", "Debase", "Sully", "Taint", "Tarnish"],
    "Stupid or Foolish": [
        "Asinine",
        "Fatuous",
        "Imbecile",
        "Inane",
        "Oafish",
        "Obtuse",
    ],
    "Sulking or Bad Tempered": [
        "Dour",
        "Morose",
        "Peevish",
        "Petulant",
        "Pout",
        "Saturnine",
        "Sullen",
        "Surly",
    ],
    "Tempt or Plot or Trick(-)": [
        "Allure",
        "Beguile",
        "Collude",
        "Connive",
        "Conspire",
        "Entice",
        "Lure",
        "Ploy",
        "Ruse",
        "Scheme",
        "Tactic",
    ],
    "To See": ["Behold", "Discern", "Espy", "Perceive", "Imperceptible(Opposite)"],
    "Uncover A Secret": ["Ferret", "Unearth", "Unravel"],
    "Unmatched or Unique": ["Inimitable", "Peerless"],
}
