List8 = {
    "Acting Properly or Misbehave(opposite)": [
        "Decorous",
        "Demure",
        "Prim",
        "Propriety",
        "Seemly",
        "Execrable(Opposite)",
        "Flagrant(Opposite)",
        "Malfeasance(Opposite)",
        "Unbecoming(Opposite)",
    ],
    "Chaos or Confusion": [
        "Bedlam",
        "Pandemonium",
        "Tumultuous",
        "Turbulence",
        "Turmoil",
        "Upheaval",
        "Welter",
    ],
    "Cheat or deceive": [
        "Artful",
        "Artifice",
        "Bilk",
        "Chicanery",
        "Crafty",
        "Duplicity",
        "Fleece",
        "Guile",
        "Gulled",
        "Hoodwink",
        "Mislead",
        "Swindle",
        "Wily",
    ],
    "Criminals or Law Breakers": ["Felon", "Menace", "Miscreant", "Rogue", "Scoundrel"],
    "Disaster": ["Calamitous", "Cataclysm", "Catastrophe", "Debacle", "Coup(Opposite)"],
    "Disregard": ["Discount", "Brush Aside"],
    "Doubtful": ["Apprehensive", "Cynical", "Dubious", "Questionable", "Skeptical"],
    "Generous Supporter": [
        "Altruist",
        "Benefactor",
        "Beneficent",
        "Benevolent",
        "Humane",
        "Magnanimous",
        "Munificent",
        "Patron",
        "Philanthropist",
    ],
    "Lack Of Respect": [
        "Audacious",
        "Brazen",
        "Cheeky",
        "Effrontery",
        "Gall",
        "Impertinent",
        "Impudent",
        "Insolent",
        "Nerve",
        "Presumptuous",
        "Temerity",
    ],
    "Overly Proud": [
        "Arrogant",
        "Bombastic",
        "Braggart",
        "Bravado",
        "Conceited",
        "Egotistical",
        "Haughty",
        "Hubris",
        "Pompous",
        "Supercilious",
        "Swagger",
        "Vainglorious",
        "Unassuming(Opposite)",
        "Elitist",
    ],
    "Practically or Possible": [
        "Conceivable",
        "Credible",
        "Feasible",
        "Plausible",
        "Pragmatic",
        "Utilitarian",
        "Verisimilar",
        "Viable",
    ],
    "Pretense Of Morality(-)": [
        "Cant",
        "Hypocritical",
        "Prig",
        "Prude",
        "Sanctimonious",
    ],
    "Repeat": ["Recapitulate", "Rehash", "Reiterate"],
    "Self Control": [
        "Abstemious",
        "Abstinence",
        "Celibacy",
        "Forbear",
        "Moderate",
        "Refrain",
        "Temperate",
    ],
    "Shining": ["Effulgent", "Luminous", "Lustrous", "Scintillating"],
    "Show-off(-)": [
        "Flamboyance",
        "Flaunt",
        "Grandiloquent",
        "Grandiose",
        "Ostentatious",
        "Pretentious",
        "Panache(+)",
    ],
    "Speak Less or Few Words": [
        "Abbreviated",
        "Abridge",
        "Brevity",
        "Condense",
        "Laconic",
        "Monosyllabic",
        "Pithy",
        "Reticent",
        "Succinct",
        "Taciturn",
    ],
    "Talkative or Lots Of Words": [
        "Garrulous",
        "Loquacious",
        "Prolix",
        "Verbiage",
        "Verbose",
        "Voluble",
        "Long-winded",
    ],
    "To Give Control or Responsibility": ["Delegate", "Devolve"],
    "Without Deception": [
        "Dupe",
        "Artless",
        "Credence or Credible",
        "Credulous",
        "Guileless",
        "Gullible",
        "Naive or Naivete",
        "Ingenuous",
    ],
}
