List7 = {
    "Boring and Repetitious": ["Monotonous", "Plod", "Tedious"],
    "Clear ( Both Physically and in Meaning)": [
        "Clarity",
        "Elucidate",
        "Exposition",
        "Expound",
        "Limpid",
        "Lucid",
        "Pellucid",
    ],
    "Correct or Repair": [
        "Amend",
        "Atone",
        "Disabuse",
        "Expiate",
        "Indemnify",
        "Redemption",
        "Redress",
        "Reparation",
        "Restitution",
    ],
    "Difficult": [
        "Arduous",
        "Cumbersome",
        "Encumber",
        "Exacting",
        "Onerous",
        "Ponderous",
        "Facile(Opposite)",
        "Laborious",
    ],
    "Difficulty or Confusing Situation": [
        "Dilemma",
        "Plight",
        "Predicament",
        "Quandary",
    ],
    "Disloyalty": ["Betray", "Perfidy", "Fealty(Opposite)", "Fidelity(Opposite)"],
    "Experienced": ["Seasoned", "Veteran"],
    "Expert": ["Connoisseur", "Layperson(Opposite)", "Virtuoso"],
    "Feeling Guilty": ["Contrite", "Penitent", "Remorse", "Rueful"],
    "Happening Before Main Event": [
        "Antecedent",
        "Forerunner",
        "Harbinger",
        "Precedent",
        "Precursor",
        "Antedate",
    ],
    "Harmful or Curse": [
        "Anathema",
        "Baleful",
        "Bane",
        "Blight",
        "Deleterious",
        "Detrimental",
        "Malediction",
        "Malignant",
        "Pernicious",
        "Insidious",
    ],
    "Idealistic": ["Quixotic", "Utopian"],
    "Immoral": [
        "Debauchery",
        "Decadent",
        "Degenerate",
        "Depravity",
        "Dissolute",
        "Improbity",
        "Wayward",
    ],
    "Interval or Pause": ["Abeyance", "Hiatus", "Lull", "Moratorium", "Respite"],
    "Just Beginning or Developing": [
        "Embryonic",
        "Fledgling",
        "Inchoate",
        "Incipient",
        "Nascent",
        "Rudimentary",
    ],
    "Lose Strength or Weaken": [
        "Atrophy",
        "Attenuate",
        "Attrition",
        "Debilitate",
        "Degenerate",
        "Degradation",
        "Effete",
        "Enervate",
        "Enfeeble",
        "Flagging",
        "Sup",
        "Wilt",
        "Wither",
    ],
    "Restrain or Set Free (Opposite)": [
        "Bridle",
        "Circumscribe",
        "Constraint",
        "Fetter",
        "Rein",
        "Secure",
        "Shackle",
        "Extricate(Opposite)",
        "Manacle",
        "Emancipate(Opposite)",
    ],
    "Right To Vote": ["Enfranchise", "Suffrage"],
    "Strange": ["Eccentric", "Foible", "Idiosyncrasy", "Quirkiness"],
    "Summary": ["Crux", "Gist", "Precis", "Purport", "Synopsis"],
    "Thriving or Restored": [
        "Burgeon",
        "Regenerate",
        "Rejuvenate",
        "Resuscitation",
        "Revive",
    ],
    "Unclear or Hazy": [
        "Amorphous",
        "Becloud",
        "Cloud",
        "Indistinct",
        "Murky",
        "Nebulous",
    ],
    "Without Mistakes or Perfect": [
        "Flawless",
        "Immaculate",
        "Impeccable",
        "Infallible",
        "Integrity",
        "Irreproachable",
        "Probity",
        "Rectitude",
        "Unimpeachable",
    ],
}
