List1 = {
    "Attractive": ["Aesthetic", "Comely"],
    "avoid or Dodge": [
        "Avert",
        "Circumvent",
        "Deflect",
        "Elude",
        "Evade or Evasive",
        "Parry",
        "Shirk",
        "Shunt",
        "Skirt",
        "Swerve",
        "Quibble",
        "Head-On(Opposite)",
        "Inevitable(Opposite)",
        "Unavoidable(Opposite)",
    ],
    "Awkward or Clumsy": ["Fumble", "Gauche", "Gawky", "Ungainly"],
    "Be Slow or Waste Of Time": [
        "Dally",
        "Dilatory",
        "Dawdle",
        "Dilly Dally",
        "Laggard",
        "Linger",
        "Malinger",
    ],
    "Detailed Knowledge or Intellectual": ["Cerebral", "Erudite", "Pundit"],
    "Flexible": ["Limber", "Lithe", "Nimble", "Supple"],
    "Foolish Talk": [
        "Babble",
        "Blather",
        "Drawl",
        "Drivel",
        "Gibberish",
        "Jabber",
        "Nonsensical",
        "Prate",
        "Prattle",
    ],
    "Having Twists or Turns": [
        "Circuitous",
        "Convoluted",
        "Intertwined",
        "Involved",
        "Meander",
        "Sinuous",
        "Tortuous",
    ],
    "Horrifying or Shocking": [
        "Aghast",
        "Appalling",
        "Egregious",
        "Ghastly",
        "Grisly",
        "Gross",
        "Grotesque",
        "Gruesome",
        "Heinous",
        "Hideous",
        "Horrendous",
        "Monstrous",
        "Morbid",
        "Unsightly",
        "Vile",
    ],
    "Inclination": [
        "Affinity",
        "Aptitude",
        "Bent",
        "Disposed",
        "Penchant",
        "Predilection",
        "Predisposition",
        "Proclivity",
        "Propensity",
    ],
    "Ineffective": ["Futile", "Ineffectual", "Efficacy(Opposite)", "Feckless"],
    "Optimistic": ["Buoyant", "Sanguine"],
    "Prediction": [
        "Augur or Augury",
        "Forecast",
        "Foresight or Foresee",
        "Foretell",
        "Presage",
        "Prescience",
        "Prognosis",
    ],
    "Separate or Not Connected": [
        "Disjointed",
        "Polarize",
        "Segregated",
        "Nexus(Opposite)",
    ],
    "Sign(Warning) (-)": [
        "Forebode",
        "Foreshadow",
        "Portend",
        "Portent",
        "Premonition",
    ],
    "Skillful": [
        "Adept",
        "Adroit",
        "Agile",
        "Consummate",
        "Deft",
        "Dexterous",
        "Proficient",
        "Prowess",
        "Inept(Opposite)",
        "Maladroit(Opposite)",
    ],
    "Spread": ["Diffuse", "Disseminate", "Promulgate", "Propagate"],
    "Threatening": ["Ominous", "Sinister", "Intimidate"],
    "To do with teaching": ["Pedantic", "Didactic", "Sophist"],
    "Very Angry": [
        "Enrage",
        "Fume",
        "Glower",
        "Incense",
        "Infuriate",
        "Irate",
        "Ire",
        "Livid",
        "Rabid",
        "Seethe",
        "Smolder",
        "Wrath",
    ],
    "Very Talent(Child)": ["Prodigy", "Precocious"],
}
