List5 = {
    "Cannot be Defeated": ["Impervious", "Indomitable", "Invincible"],
    "Combine": ["Amalgamate", "Coalition", "Meld", "Synthesis"],
    "Excess": [
        "Abound",
        "Barrage",
        "Bounteous",
        "Copious",
        "Glut",
        "Inundate",
        "Myriad",
        "Plethora",
        "Profuse",
        "Prolific",
        "Steeped",
        "Surfeit",
        "Surge",
        "Teeming",
    ],
    "Excessive Patriotism (-)": [
        "Chauvinism",
        "Fanatic",
        "Jingoism",
        "Zealot",
        "Idealogue",
    ],
    "Explain Too Much": ["Belabor", "Understatement(Opposite)"],
    "Increase": [
        "Accretion",
        "Aggrandize",
        "Augment",
        "Ballon",
        "Dilate",
        "Enhance",
        "Mounting",
        "Proliferate",
        "Wax",
    ],
    "Lessen In Intensity": ["Abate", "Ebb", "Recede", "Subside"],
    "Lucky or Unlucky": [
        "Fortuitous",
        "Opportune",
        "Propitious",
        "Serendipity",
        "Despair(Opposite)",
        "Hapless(Opposite)",
        "Wretched(Opposite)",
    ],
    "Nervous or Restless": ["Restive", "Skittish"],
    "Pain or Suffering": [
        "Adversity",
        "Afflictions",
        "Mishap",
        "Ordeals",
        "Trials",
        "Tribulation",
    ],
    "Poor": [
        "Bankrupt",
        "Destitute",
        "Impecunious",
        "Impoverished",
        "Indigent",
        "Insolvent",
        "Penury",
        "Solvent(Opposite)",
    ],
    "Reduce or Restrict": [
        "Constrict",
        "Contract",
        "Curtail",
        "Dwindle",
        "Flag",
        "Wane",
    ],
    "Relevant": ["Apposite", "Apropos", "Germane", "Pertinent"],
    "Remembering The Past": [
        "Evocative",
        "Hindsight",
        "Nostalgia",
        "Reminiscence",
        "Retrospect",
        "Wistful",
    ],
    "Routine Behavior": ["Obtain", "Wont"],
    "Shortage or Lack of": ["Dearth", "Deficit", "Paucity", "Vacuous"],
    "Spend Too Much or Waste(-)": [
        "Prodigal",
        "Profligate",
        "Spendthrift",
        "Squander",
        "Extravagance",
        "Lavish",
    ],
    "Sure or Certain or Conditional(Opposite)": [
        "Absolute",
        "Categorical",
        "Certitude",
        "Conviction",
        "Emphatic",
        "Incontrovertible",
        "Unqualified",
        "Contingent(Opposite)",
        "Provisional(Opposite)",
        "Qualify(Opposite)",
        "Tentative(Opposite)",
    ],
    "Unclear In Meaning": ["Ambivalent", "Ambiguous", "Equivocal"],
    "Unwilling To Spend(-)": [
        "Closefisted",
        "Miserly",
        "Niggardly",
        "Parsimonious",
        "Skinflint",
        "Stingy",
        "Stint",
        "Tightfisted",
        "Thrift",
        "Frugal",
        "Husbandry",
        "Economical or Economy",
    ],
    "Very High Price(-)": ["Exorbitant", "Gouging", "Prohibitive"],
    "Very Less(-)": [
        "Exiguous",
        "Meager",
        "Puny",
        "Scanty",
        "Skimpy",
        "Spare",
        "Sparse",
    ],
    "Wealthy": ["Opulent", "Affluent"],
}
