List3 = {
    "Aggressive or Argumentative": [
        "Bellicose",
        "Belligerent",
        "Contentious",
        "Disputatious",
        "Fractious",
        "Hostility",
        "Litigious",
        "Polemical",
        "Pugnacious",
        "Truculent",
    ],
    "Agreement or Harmony": [
        "Accord",
        "Concord",
        "Conformity",
        "Congruous",
        "Consonance",
        "Discord(Opposite)",
        "Dissonance(Opposite)",
        "Faction(Opposite)",
        "Incompatible(Opposite)",
        "Discrepancy(Opposite)",
        "Irreconcilable(Opposite)",
    ],
    "Argue or Fight": [
        "Altercation",
        "Bicker",
        "Brawl",
        "Combat",
        "Contend",
        "Row",
        "Scuffle",
        "Squabble",
        "Tiff",
        "Tussle",
        "Truce(Opposite)",
    ],
    "Being Alike": ["Homogeneity", "Uniformity", "Heterogeneity(Opposite)"],
    "Biased": [
        "Bigot",
        "Discriminatory",
        "Prejudiced",
        "Partisan",
        "Disinterested(Opposite)",
        "Tendentious",
    ],
    "Calm": [
        "Aplomb",
        "Composure",
        "Equanimity",
        "Impassive",
        "Imperturbable",
        "Nonchalant",
        "Phlegmatic",
        "Placid",
        "Serene",
        "Staid",
        "Stolid",
        "Tranquil",
    ],
    "Confuse": [
        "Astound",
        "Baffle",
        "Befuddle",
        "Bemuse",
        "Bewilder",
        "Confound",
        "Flabbergasted",
        "Foxed",
        "Nonplussed",
        "Obfuscated",
        "Perplex",
        "Stupefy",
    ],
    "Disturbed or Agitated": [
        "Consternation",
        "Disconcert",
        "Dismay",
        "Distraught",
        "Faze",
        "Fluster",
        "Frenetic",
        "Hysterical",
        "Implacable",
        "Overwrought",
        "Perturb",
        "Disquiet",
    ],
    "Dominating(-)": [
        "Absolute",
        "Authoritative",
        "Autocrat",
        "Despot",
        "Dogmatic",
        "Hegemony",
        "Imperious",
        "Martinet",
        "Totalitarian",
        "Tyrant",
        "Doctrinaire",
    ],
    "Easily noticeable": ["Patent", "Conspicuous", "Prominent"],
    "Equality": [
        "Commensurate",
        "Parity",
        "Peers",
        "Disparate(Opposite)",
        "Tantamount",
    ],
    "Excessive Flattery": ["Fawn", "Fulsome", "Obsequious", "Sycophant", "Adulation"],
    "Impartial": [
        "Dispassionate",
        "Egalitarian",
        "Equitable",
        "Evenhanded",
        "Objectivity",
    ],
    "Include Everything": ["Comprehensive", "Encompass", "Expansive", "Pervasive"],
    "Indifferent": ["Apathy", "Stoic"],
    "Insulting Words": ["Deprecatory", "Derogatory", "Pejorative"],
    "Make Hostile": ["Alienate", "Antagonize", "Estrange"],
    "Narrow Minded or Regional": ["Insular", "Myopic", "Parochial", "Provincial"],
    "Not Serious or Disrespect": [
        "Flippant",
        "Frivolous or Frivolity",
        "Insouciant",
        "Levity",
        "Grave or Gravity(Opposite)",
        "Blithe",
        "Facetious",
    ],
    "Overly Obedient(-)": ["Grovel", "Servile", "Slavish", "Subservient", "Supplicant"],
    "Present Everywhere": ["Omnipresent", "Ubiquitous"],
    "Split or Gap": ["Chasm", "Dichotomy", "Gulf", "Rift", "Schism"],
    "Suppress or End": ["Quash", "Quell", "Repress", "Scotch", "Subdue"],
    "To Come Out From": ["Emanate", "Emit"],
}
