List2 = {
    "Bitter feelings or Ill will": [
        "Malevolence",
        "Malice",
        "Rancor",
        "Vicious",
        "Virulent",
    ],
    "Cautions or Careful or Risky(Opposite)": [
        "Chary",
        "Circumspect",
        "Gingerly",
        "Heedful",
        "Leery",
        "Prudent",
        "Wary",
        "Daredevil(Opposite)",
        "Folly(Opposite)",
        "Foolhardy(Opposite)",
        "Rash(Opposite)",
        "Reckless(Opposite)",
        "Caveat",
    ],
    "Coming Together": ["Coalesce", "Rally"],
    "Complain(Low Degree)": ["Captious", "Carping", "Grouse", "Querulous"],
    "Danger": ["Jeopardy", "Pitfall", "Precarious", "Snare"],
    "Disapprove or Scold": [
        "Assail",
        "Berate",
        "Castigate",
        "Decry",
        "Denounce",
        "Denunciation",
        "Diatribe",
        "Epithet",
        "Excoriate",
        "Fulminate",
        "Invective",
        "Lambaste",
        "Rant",
        "Rile",
        "Revile",
        "Tirade",
        "Upbraid",
        "Vituperative",
    ],
    "Emphasize": ["Accentuate", "Foreground", "Underscore"],
    "Hate": [
        "Abhor",
        "Animosity",
        "Antipathy",
        "Aversion",
        "Despicable",
        "Detest",
        "Loathe",
        "Odious",
        "Repel",
        "Repugnant",
        "Repulsion",
    ],
    "Minor Scolding or Warning": [
        "Admonish",
        "Censure",
        "Chastise",
        "Chide",
        "Rebuke",
        "Reprimand",
        "Reproach",
        "Reprove",
    ],
    "Mock or Disrespect(-)": [
        "Abase",
        "Belittle",
        "Condescend",
        "Contempt",
        "Denigrate",
        "Deride",
        "Disdain",
        "Disparage",
        "Jeer",
        "Lampon",
        "Patronize",
        "Sarcastic",
        "Sardonic",
        "Satire",
        "Scoff",
        "Scorn",
        "Sneer",
        "Snicker",
        "Snide",
        "Spurn",
        "Taunt",
        "Banter(+)",
        "Raillery(+)",
    ],
    "Old Fashioned or Outdated": [
        "Antediluvian",
        "Antiquated",
        "Archaic",
        "Dated",
        "Obsolete",
        "Outmode",
        "Quaint",
    ],
    "Praise": [
        "Acclaim",
        "Accolade",
        "Applaud",
        "Approbation",
        "Commendable",
        "Eulogy",
        "Exalt",
        "Extol",
        "Glorify",
        "Hail",
        "Laud",
        "Lionize",
        "Plaudit",
        "Encomiastic",
    ],
    "Rebellious or Unconventional": [
        "Dissident",
        "Heresy",
        "Heretical",
        "Heterodox",
        "Iconoclast",
        "Insurgent",
        "Insurrection",
        "Maverick",
        "Nonconformist",
        "Radical",
        "Reactionary(Opposite)",
        "Renegade",
        "Revolutionary",
        "Subversive",
        "Conservative(Opposite)",
        "Conventional(Opposite)",
        "Orthodox(Opposite)",
        "Hidebound",
    ],
    "Rule or Principle": [
        "Axioms",
        "Canons",
        "Dictum",
        "Doctrine",
        "Dogmas",
        "Mandate",
        "Tenets",
        "Ideology",
    ],
    "Self-Satisfaction(-)": ["Gloat", "Smirk", "Smug", "Bask(+)", "Complacent"],
    "Similarity": ["Analogy", "Antithetical(Opposite)"],
    "Time Related Words": ["Anachronism", "Chronicle", "Chronological"],
    "To Defeat or Surrender": [
        "Drub",
        "Pulverize",
        "Rout",
        "Subjugate",
        "Vanquish",
        "Capitulate",
    ],
    "Troubled": ["Beset", "Beleaguered", "Plagued"],
}
