List13 = {
    "Activate or Speed Up": [
        "Catalyst",
        "Engender",
        "Expedite",
        "Facilitate",
        "Kindle",
        "Precipitate",
        "Prod",
        "Prompt",
        "Propel",
        "Spur",
        "Stimulate",
    ],
    "Attractive or Decorative": [
        "Adorn",
        "Embellish",
        "Florid",
        "Garnish",
        "Ornate",
        "Resplendent",
        "Spectacular",
    ],
    "Ban": ["Interdict", "Sanction", "Veto"],
    "Blameworthy or Guilty": ["Culpable", "Reprehensible"],
    "Can’t Decide or Fickle": [
        "Arbitrary",
        "Capricious",
        "Erratic",
        "Inconsistent",
        "Irresolute",
        "Mercurial",
        "Oscillate",
        "Sway",
        "Temperamental",
        "Vacillate",
        "Volatile",
        "Waffle",
        "Waver",
        "Whimsical",
    ],
    "Careless or Dirty": [
        "Disheveled",
        "Rumpled",
        "Shabby",
        "Shoddy",
        "Sloppy",
        "Slovenly",
        "Unkempt",
    ],
    "Confirm or Support": [
        "Affirm",
        "Clinch",
        "Corroborate",
        "Endorse",
        "Ratify",
        "Substantiate",
        "Testify",
        "Validate",
        "Unfounded (Opposite)",
    ],
    "Dead End": ["Impasse", "Stalemate"],
    "Disrespecting Sacred Things": [
        "Blasphemy",
        "Desecrate",
        "Impious",
        "Profane",
        "Sacrilege",
        "Consecrate (Opposite)",
        "Sacrosanct (Opposite)",
        "Anoint (Opposite)",
    ],
    "Free From Blame": ["Absolve", "Acquit", "Exculpate", "Exonerate", "Vindicate"],
    "Harmless or Kind": ["Benign", "Innocuous"],
    "Helpful": ["Officious (-)", "Solicitous (+)"],
    "Left Over": ["Remnant", "Residual", "Trace", "Vestige", "Modicum (Neutral)"],
    "Mutual Agreement": ["Consensus", "Unanimous"],
    "Not Through or Superficially": ["Cursory", "Perfunctory", "Summarily"],
    "Physically Strong": ["Robust", "Rugged", "Sturdy", "Vigorous"],
    "Punish": [
        "Condemn",
        "Convict",
        "Immure",
        "Incarcerate",
        "Sentence",
        "Amnesty (Opposite)",
        "Condone (Opposite)",
        "Reprieve (Opposite)",
    ],
    "Restrict or Stop or Prevent": [
        "Check",
        "Deter",
        "Foil",
        "Forestall",
        "Frustrate",
        "Hinder",
        "Impede or Impediment",
        "Inhibit",
        "Obstruct",
        "Preclude",
        "Retard",
        "Stymie",
        "Thwart",
        "Occlude",
        "Stanch",
        "Preempt",
    ],
    "Simple or Plain or Boring": [
        "Ascetic",
        "Austere",
        "Bland",
        "Drab",
        "Insipid",
        "Prosaic",
        "Stark",
        "Vapid",
    ],
    "To Blame or Accuse or Charge": [
        "Allege or Allegation",
        "Implicate",
        "Impute",
        "Incriminate",
        "Indict",
        "Recriminate (Neutral)",
    ],
    "Unsteady Walk or Hesitate": [
        "Falter",
        "Flounder",
        "Founder",
        "Fumble",
        "To Run Around",
        "Tottering",
        "Wobbly",
    ],
    "Without Real Power": ["Figurehead", "Nominal", "Titular"],
}
